Repository SPACE-DEV-CLUB/ReadmeMaker, pull requests merged in 2022-06, with the labels that each got.

#11 Read 45 dnd기능 적용
  .eslintrc.js
  next.config.js
  package.json
  src/components/generator/DndContainer.tsx
  src/components/generator/EditorComponent.tsx
  src/components/generator/Generator.tsx
  yarn.lock
Labels: 리뷰 요청

#13 READ-47-에디터-리코일-상태분리
  src/atoms/components.ts
  src/components/generator/FilterList.tsx
  src/components/generator/Generator.tsx
  src/components/generator/ImgComponentEditor.tsx
  src/components/generator/MDViewer.tsx
  src/components/generator/PreviewContainer.tsx
  src/components/generator/SideBar.tsx
  src/components/generator/SwitchGenerator.tsx
  src/components/generator/TextComponentEditor.tsx
  src/components/generator/index.tsx
  src/hooks/useDebounce.ts
  src/pages/generator.tsx
  src/types/imgComponentType.ts
  src/types/index.ts
  src/types/textComponentType.ts
  src/utils/index.ts
  src/utils/removeComponent.ts
  src/utils/replaceText.ts
Labels: 리뷰 요청

#17 Read-48-네비게이션-바-적용
  src/components/common/NavBar.tsx
  src/components/generator/Generator.tsx
  src/components/generator/SwitchGenerator.tsx
  src/components/generator/dnd/DndContainer.tsx
  src/components/generator/editor/EditorComponent.tsx
  src/components/generator/editor/ImgComponentEditor.tsx
  src/components/generator/editor/TextComponentEditor.tsx
  src/components/generator/index.tsx
  src/components/generator/sidebar/FilterList.tsx
  src/components/generator/sidebar/SideBar.tsx
  src/components/generator/viewer/MDViewer.tsx
  src/components/generator/viewer/PreviewContainer.tsx
  src/pages/generator.tsx
  src/pages/index.tsx
Labels: 리뷰 요청

#16 fix: 카트 슬라이드, nav, filter 수정
  src/assets/CloseButton.tsx
  src/atoms/index.ts
  src/components/common/DarkModeButton.tsx
  src/components/common/ModalTemplate.tsx
  src/components/main/MainPage.tsx
  src/components/main/Modal.tsx
  src/components/main/Templates/TemplateCardContainer.tsx
  src/components/main/Templates/TemplatesContainer.tsx
  src/components/main/cart/Cart.tsx
  src/components/main/cart/CartItem.tsx
  src/components/main/components/ComponentItem.tsx
  src/components/main/components/ComponentsContainer.tsx
  src/components/main/components/FilterButton.tsx
  src/components/main/components/FilterList.tsx
  src/pages/index.tsx
Labels: 추가 구현중

#21 전체 레이아웃 통일 및 장바구니 모달 전역관리 수정
  src/atoms/index.ts
  src/components/common/DarkModeButton.tsx
  src/components/common/NavBar.tsx
  src/components/main/MainPage.tsx
  src/components/main/Templates/TemplateCardContainer.tsx
  src/components/main/Templates/TemplateCardText.tsx
  src/components/main/Templates/TemplatesContainer.tsx
  src/components/main/cart/Cart.tsx
  src/components/main/components/ComponentItem.tsx
  src/components/main/components/ComponentList.tsx
  src/components/main/components/ComponentsContainer.tsx
  src/components/main/components/FilterList.tsx
  src/components/main/components/PopularItemList.tsx
  src/pages/index.tsx
Labels: 머지요청

#20 Read-51-제너레이터-UI-변경사항
  src/assets/CartIcon.tsx
  src/components/generator/editor/TextComponentEditor.tsx
  src/components/generator/sidebar/SideBar.tsx
  src/components/generator/viewer/PreviewContainer.tsx
  src/pages/generator.tsx
  src/styles/globalStyle.tsx
Labels: 리뷰 요청

#23 Read 55 린트 재설치
  .eslintrc.js
  package.json
  src/assets/CartIcon.tsx
  src/components/common/DraggableContainer.tsx
  src/components/common/ModalTemplate.tsx
  src/components/common/NavBar.tsx
  src/components/common/NavBarMainItem.tsx
  src/components/generator/Generator.tsx
  src/components/generator/SwitchGenerator.tsx
  src/components/generator/dnd/DndComponent.tsx
  src/components/generator/dnd/DndContainer.tsx
  src/components/generator/dnd/Generator.tsx
  src/components/generator/editor/ComponentContainer.tsx
  src/components/generator/editor/EditorComponent.tsx
  src/components/generator/editor/ImgComponentEditor.tsx
  src/components/generator/editor/TextComponentEditor.tsx
  src/components/generator/sidebar/FilterList.tsx
  src/components/generator/sidebar/SideBar.tsx
  src/components/generator/viewer/MDViewer.tsx
  src/components/generator/viewer/PreviewContainer.tsx
  src/components/main/MainPage.tsx
  src/components/main/Modal.tsx
  src/components/main/Templates/Tag.tsx
  src/components/main/Templates/TemplateCardContainer.tsx
  src/components/main/Templates/TemplateCardTag.tsx
  src/components/main/Templates/TemplateCardText.tsx
  src/components/main/Templates/TemplateComponents.tsx
  src/components/main/Templates/TemplatesContainer.tsx
  src/components/main/cart/Cart.tsx
  src/components/main/cart/CartItem.tsx
  src/components/main/components/ComponentItem.tsx
  src/components/main/components/ComponentsContainer.tsx
  src/components/main/components/FilterButton.tsx
  src/components/main/components/FilterList.tsx
  src/components/main/components/PopularItem.tsx
  src/components/main/components/PopularItemList.tsx
  src/pages/_app.tsx
  src/pages/generator.tsx
  src/pages/index.tsx
  yarn.lock
Labels: 리뷰 요청

#24 Read 52 export 수정
  src/components/generator/Generator.tsx
  src/components/generator/viewer/PreviewContainer.tsx
  src/pages/generator.tsx
Labels: 리뷰 요청
